version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.1
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 4.1.1
  - dependency-name: twilio-ruby
    versions:
    - 5.46.1
    - 5.47.0
    - 5.48.0
  - dependency-name: sprockets
    versions:
    - 3.7.2
  - dependency-name: rails
    versions:
    - 4.2.11.1
  - dependency-name: turbolinks
    versions:
    - 5.2.1
  - dependency-name: rails-html-sanitizer
    versions:
    - 1.3.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: nokogiri
    versions:
    - 1.11.0
  - dependency-name: web-console
    versions:
    - 3.3.0
  - dependency-name: rack
    versions:
    - 1.6.13
  - dependency-name: i18n
    versions:
    - 0.9.5
  - dependency-name: jquery-rails
    versions:
    - 4.3.4
